### ISSUE TITLE
Create Bearer Token DevOps Task does not return $(BearerToken)

### ISSUE THREAD

**Issue by sebastianbirk** [DataThirstLtd/databricks.vsts.tools#8]
[DatabricksBearerToken.log](https://github.com/DataThirstLtd/databricks.vsts.tools/files/3887670/DatabricksBearerToken.log)

The "Databricks Create Bearer Token" task completes successfully in my pipeline but does not return the $BearerToken variable as expected. 

The log is attached.

2019-11-25T16:16:22.1789540Z ##[debug]received 628-byte response of content type text/html
2019-11-25T16:16:22.1837445Z ##[debug]Processed: ##vso[task.setVariable variable=BearerToken]

It seems suspicious that content type text/html is returned (probably an error message?)

Can you add debugging output here or help me with what could be the issue?

Many thanks
Sebastian

**Comment by simondmorias** [comment]
Confirmed bug. There is a typo in the Prod config. I will fix tomorrow. Thanks for reporting.

**Comment by simondmorias** [comment]
This has been fixed and released. If you try again and also add a powershell task with an line script that just does:
```
Write-Host $(BearerToken)
```
You should see the bearer token.
Thanks for reporting.

**Comment by sebastianbirk** [comment]
Hi Simon,

This still does not work for me. I now have version 0.8.1240 (Latest). 
The Write-Host $(BearerToken) PS task is also empty.

Best,
Sebastian

**Comment by simondmorias** [comment]
I'm still unable to reproduce. This is the code it tries to execute:

```
    [string]$region = "westeurope"
    [string]$applicationId = "xxx"
    [string]$spSecret = "YOURSECRET"
    [string]$subscriptionId = "xxx"
    [string]$tenantId = "xxx"
    [string]$resourceGroup = "xxx"
    [string]$workspace = "xxx"

    Install-Module -Name azure.databricks.cicd.tools -Force -Scope CurrentUser
  
    Connect-Databricks -ApplicationId $applicationId -Secret $spSecret -Region $region -ResourceGroupName $resourceGroup -WorkspaceName $workspace -TenantId $tenantId -SubscriptionId $subscriptionId 
   
    $Token = Invoke-DatabricksAPI  -Method POST -API "api/2.0/token/create" -Body @{}
    
    $BearerToken = $Token.token_value
    Write-Output "BearerToken: $BearerToken"
```

Could you try executing that manually in a powershell window on your desktop?

**Comment by simondmorias** [comment]
I'm also wondering if your secret contains any special characters such as =&%"?

**Comment by sebastianbirk** [comment]
The powershell script works fine with exactly the same parameters and prints out my token. With this powershell all subsequent tasks using the token are also successful.

The only difference I can see now is:

powershell: 
Install-Module -Name azure.databricks.cicd.tools -Force -Scope CurrentUser

your task: 
Import-Module -Name $PSScriptRoot\ps_modules\azure.databricks.cicd.tools\azure.databricks.cicd.tools.psm1

Can this have any effect?

My secret contains '=' and '@'.

**Comment by simondmorias** [comment]
The = sign will be the problem. The latest version of the PowerShell module includes URL encoding of the secret. But the Azure DevOps task has a slightly older version that is missing that encoding.
I will recompile and deploy. For now you could try generating a new token that doesn't include those characters.

**Comment by simondmorias** [comment]
New version deployed can you try again?

**Comment by sebastianbirk** [comment]
It works now. Thank you!
